import type { Metadata } from "next";
import PasswordGenerator from "../password-generator/components/PasswordGenerator";

export const metadata: Metadata = {
  title: "Strong Password Generator — Passwords That Take Centuries to Crack | EveryFreeTool",
  description: "Generate passwords strong enough to resist GPU cracking farms. 16+ characters, CSPRNG-powered, with real-time strength analysis. See exactly how long your password would take to crack.",
  openGraph: { title: "Strong Password Generator — Centuries to Crack", description: "Generate passwords that would take centuries to crack. Real-time entropy and crack time analysis. Free, no signup, 100% client-side.", type: "website" },
  robots: "index, follow",
};

export default function StrongPasswordGeneratorPage() {
  const faqs = [
    { name: "What defines a 'strong' password?", text: "A strong password has high entropy — meaning it's highly unpredictable. Quantitatively, 60+ bits of entropy is moderate, 80+ is strong, and 128+ is effectively uncrackable. A 16-character random password with all character types has about 105 bits of entropy." },
    { name: "How fast can passwords be cracked in 2025?", text: "Modern GPU clusters can test over 100 billion password hashes per second against fast algorithms like MD5. Even slower algorithms like bcrypt can be attacked at thousands of attempts per second. This is why password length and randomness are critical." },
    { name: "Is 8 characters enough?", text: "No. An 8-character password using all character types has about 52 bits of entropy and can be cracked in under an hour with modern hardware. NIST and OWASP now recommend 16+ characters as the baseline for security." },
    { name: "What do NIST guidelines recommend?", text: "NIST SP 800-63B recommends passwords of at least 8 characters (their minimum for online services) but encourages longer passwords. They emphasize that password length is the primary strength factor and recommend allowing up to 64+ characters." },
    { name: "How do I make the strongest possible password?", text: "Use 20+ characters with all character types (uppercase, lowercase, numbers, symbols) generated by a CSPRNG. Or use a 6-7 word passphrase from a curated wordlist. Store it in a password manager and enable 2FA on the account." },
  ];
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org", "@type": "WebApplication",
        name: "Strong Password Generator",
        url: "https://everyfreetool.com/utility-tools/strong-password-generator",
        description: "Generate passwords strong enough to resist modern GPU cracking. Real-time entropy calculation and crack time estimates. Free, 100% client-side.",
        applicationCategory: "UtilityApplication", operatingSystem: "Any",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        creator: { "@type": "Organization", name: "EveryFreeTool", url: "https://everyfreetool.com" },
      }) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org", "@type": "FAQPage",
        mainEntity: faqs.map(f => ({ "@type": "Question", name: f.name, acceptedAnswer: { "@type": "Answer", text: f.text } })),
      }) }} />
      <div className="min-h-screen" style={{ backgroundColor: "var(--bg)", color: "var(--text)" }}>
        <div className="max-w-[800px] mx-auto px-4 py-8 md:py-12">
          <nav className="flex items-center gap-1 mb-4" style={{ color: "var(--text-muted)" }}>
            <a href="/" className="hover:underline" style={{ color: "#059669" }}>Home</a><span>/</span><span>Utility Tools</span>
          </nav>
          <h1 className="text-3xl md:text-4xl font-bold mb-3">Strong Password Generator &mdash; Passwords That Take Centuries to Crack</h1>
          <p className="text-lg mb-8" style={{ color: "var(--text-muted)" }}>Generate passwords with enough entropy to withstand modern GPU cracking farms. See real-time strength analysis with crack time estimates for four attack scenarios.</p>
          <article className="space-y-6 mb-10">
            <section className="rounded-xl border p-5" style={{ backgroundColor: "var(--surface)", borderColor: "var(--border)" }}>
              <h2 className="text-[22px] sm:text-[28px] font-bold mb-3">Password Strength by the Numbers</h2>
              <p className="leading-relaxed mb-3" style={{ fontSize: "17px", lineHeight: "1.7", color: "var(--text-muted)" }}>Password strength is measured in <strong style={{ color: "var(--text)" }}>bits of entropy</strong>. Each bit doubles the number of possible passwords an attacker must try. Here&apos;s what different entropy levels mean in practice:</p>
              <div className="space-y-2" style={{ fontSize: "17px", lineHeight: "1.7", color: "var(--text-muted)" }}>
                <p><strong style={{ color: "#DC2626" }}>Under 40 bits:</strong> Cracked in seconds to minutes. Common passwords, short PINs, simple patterns.</p>
                <p><strong style={{ color: "#D97706" }}>40-59 bits:</strong> Cracked in hours to days. Short passwords with mixed character types.</p>
                <p><strong style={{ color: "#65A30D" }}>60-79 bits:</strong> Cracked in years to decades. Moderate random passwords, 5-word passphrases.</p>
                <p><strong style={{ color: "#059669" }}>80-127 bits:</strong> Cracked in centuries to millennia. Strong random passwords, 6-7 word passphrases.</p>
                <p><strong style={{ color: "#059669" }}>128+ bits:</strong> Effectively uncrackable. Beyond brute force capability of any known technology.</p>
              </div>
            </section>
            <section className="rounded-xl border p-5" style={{ backgroundColor: "var(--surface)", borderColor: "var(--border)" }}>
              <h2 className="text-[22px] sm:text-[28px] font-bold mb-3">Why 16+ Characters Is the New Baseline</h2>
              <p className="leading-relaxed" style={{ fontSize: "17px", lineHeight: "1.7", color: "var(--text-muted)" }}>In 2020, 8 characters was considered acceptable. By 2025, GPU cracking speeds have made 8-character passwords trivially breakable. NIST, OWASP, and security researchers now recommend <strong style={{ color: "var(--text)" }}>16 characters minimum</strong> for important accounts. Our generator defaults to 16 characters with all character types &mdash; providing approximately 105 bits of entropy. That would take longer than the age of the universe to crack with current technology.</p>
            </section>
          </article>
          <div className="rounded-xl border p-4 mb-8 text-center" style={{ backgroundColor: "#0596691a", borderColor: "#05966940" }}>
            <p className="font-semibold" style={{ fontSize: "17px" }}>A strong password is already generated below &mdash; copy it or customize the settings.</p>
          </div>
        </div>
      </div>
      <PasswordGenerator title="Strong Password Generator" subtitle="Passwords strong enough to resist any known attack. CSPRNG-powered, real-time strength analysis." defaultMode="random" articleMode={true} />
    </>
  );
}
